<?php

return [
    'states' => [
        'Abia' => [
            'capital' => 'Umuahia',
            'lgas' => [
                'Aba North',
                'Aba South',
                'Arochukwu',
                'Bende',
                'Ikwuano',
                'Isiala Ngwa North',
                'Isiala Ngwa South',
                'Isuikwuato',
                'Obi Ngwa',
                'Ohafia',
                'Osisioma Ngwa',
                'Ugwunagbo',
                'Ukwa East',
                'Ukwa West',
                'Umuahia North',
                'Umuahia South',
                'Umu Nneochi',
            ],
        ],
        'Adamawa' => [
            'capital' => 'Yola',
            'lgas' => [
                'Demsa',
                'Fufore',
                'Ganye',
                'Girei',
                'Gombi',
                'Guyuk',
                'Hong',
                'Jada',
                'Lamurde',
                'Madagali',
                'Maiha',
                'Mayo Belwa',
                'Michika',
                'Mubi North',
                'Mubi South',
                'Numan',
                'Shelleng',
                'Song',
                'Toungo',
                'Yola North',
                'Yola South',
            ],
        ],
        'Akwa Ibom' => [
            'capital' => 'Uyo',
            'lgas' => [
                'Abak',
                'Eastern Obolo',
                'Eket',
                'Esit Eket',
                'Essien Udim',
                'Etim Ekpo',
                'Etinan',
                'Ibeno',
                'Ibesikpo Asutan',
                'Ibiono Ibom',
                'Ika',
                'Ikono',
                'Ikot Abasi',
                'Ikot Ekpene',
                'Ini',
                'Itu',
                'Mbo',
                'Mkpat Enin',
                'Nsit Atai',
                'Nsit Ibom',
                'Nsit Ubium',
                'Obot Akara',
                'Okobo',
                'Onna',
                'Oron',
                'Oruk Anam',
                'Udung Uko',
                'Ukanafun',
                'Uruan',
                'Urue-Offong/Oruko',
                'Uyo',
            ],
        ],
        'Anambra' => [
            'capital' => 'Awka',
            'lgas' => [
                'Aguata',
                'Anambra East',
                'Anambra West',
                'Anaocha',
                'Awka North',
                'Awka South',
                'Ayamelum',
                'Dunukofia',
                'Ekwusigo',
                'Idemili North',
                'Idemili South',
                'Ihiala',
                'Njikoka',
                'Nnewi North',
                'Nnewi South',
                'Ogbaru',
                'Onitsha North',
                'Onitsha South',
                'Orumba North',
                'Orumba South',
                'Oyi',
            ],
        ],
        'Bauchi' => [
            'capital' => 'Bauchi',
            'lgas' => [
                'Alkaleri',
                'Bauchi',
                'Bogoro',
                'Damban',
                'Darazo',
                'Dass',
                'Gamawa',
                'Ganjuwa',
                'Giade',
                'Itas/Gadau',
                'Jama\'are',
                'Katagum',
                'Kirfi',
                'Misau',
                'Ningi',
                'Shira',
                'Tafawa Balewa',
                'Toro',
                'Warji',
                'Zaki',
            ],
        ],
        'Bayelsa' => [
            'capital' => 'Yenagoa',
            'lgas' => [
                'Brass',
                'Ekeremor',
                'Kolokuma/Opokuma',
                'Nembe',
                'Ogbia',
                'Sagbama',
                'Southern Ijaw',
                'Yenagoa',
            ],
        ],
        'Benue' => [
            'capital' => 'Makurdi',
            'lgas' => [
                'Ado',
                'Agatu',
                'Apa',
                'Buruku',
                'Gboko',
                'Guma',
                'Gwer East',
                'Gwer West',
                'Katsina-Ala',
                'Konshisha',
                'Kwande',
                'Logo',
                'Makurdi',
                'Obi',
                'Ogbadibo',
                'Oju',
                'Okpokwu',
                'Ohimini',
                'Oturkpo',
                'Tarka',
                'Ukum',
                'Ushongo',
                'Vandeikya',
            ],
        ],
        'Borno' => [
            'capital' => 'Maiduguri',
            'lgas' => [
                'Abadam',
                'Askira/Uba',
                'Bama',
                'Bayo',
                'Biu',
                'Chibok',
                'Damboa',
                'Dikwa',
                'Gubio',
                'Guzamala',
                'Gwoza',
                'Hawul',
                'Jere',
                'Kaga',
                'Kala/Balge',
                'Konduga',
                'Kukawa',
                'Kwaya Kusar',
                'Mafa',
                'Magumeri',
                'Maiduguri',
                'Marte',
                'Mobbar',
                'Monguno',
                'Ngala',
                'Nganzai',
                'Shani',
            ],
        ],
        'Cross River' => [
            'capital' => 'Calabar',
            'lgas' => [
                'Abi',
                'Akamkpa',
                'Akpabuyo',
                'Bakassi',
                'Bekwarra',
                'Biase',
                'Boki',
                'Calabar Municipal',
                'Calabar South',
                'Etung',
                'Ikom',
                'Obanliku',
                'Obubra',
                'Obudu',
                'Odukpani',
                'Ogoja',
                'Yakuur',
                'Yala',
            ],
        ],
        'Delta' => [
            'capital' => 'Asaba',
            'lgas' => [
                'Aniocha North',
                'Aniocha South',
                'Bomadi',
                'Burutu',
                'Ethiope East',
                'Ethiope West',
                'Ika North East',
                'Ika South',
                'Isoko North',
                'Isoko South',
                'Ndokwa East',
                'Ndokwa West',
                'Okpe',
                'Oshimili North',
                'Oshimili South',
                'Patani',
                'Sapele',
                'Udu',
                'Ughelli North',
                'Ughelli South',
                'Ukwuani',
                'Uvwie',
                'Warri North',
                'Warri South',
                'Warri South West',
            ],
        ],
        'Ebonyi' => [
            'capital' => 'Abakaliki',
            'lgas' => [
                'Abakaliki',
                'Afikpo North',
                'Afikpo South',
                'Ebonyi',
                'Ezza North',
                'Ezza South',
                'Ikwo',
                'Ishielu',
                'Ivo',
                'Izzi',
                'Ohaozara',
                'Ohaukwu',
                'Onicha',
            ],
        ],
        'Edo' => [
            'capital' => 'Benin City',
            'lgas' => [
                'Akoko-Edo',
                'Egor',
                'Esan Central',
                'Esan North-East',
                'Esan South-East',
                'Esan West',
                'Etsako Central',
                'Etsako East',
                'Etsako West',
                'Igueben',
                'Ikpoba-Okha',
                'Oredo',
                'Orhionmwon',
                'Ovia North-East',
                'Ovia South-West',
                'Owan East',
                'Owan West',
                'Uhunmwonde',
            ],
        ],
        'Ekiti' => [
            'capital' => 'Ado-Ekiti',
            'lgas' => [
                'Ado',
                'Ekiti-East',
                'Ekiti-West',
                'Emure/Ise/Orun',
                'Ekiti South-West',
                'Ikere Ekiti',
                'Irepodun',
                'Ijero,',
                'Ido/Osi',
                'Oye',
                'Ikole',
                'Moba',
                'Gbonyin',
                'Efon',
                'Ise/Orun',
                'Ilejemeje.'
            ],

        ],
        'FCT - Abuja' => [
            'capital' => '',
            'lgas' => [
                'Abaji',
            'Abuja Municipal',
            'Bwari',
            'Gwagwalada',
            'Kuje',
            'Kwali'
            ],
            
        ],
        'Gombe' => [
            'capital' => '',
            'lgas' => [
                'Akko',
                'Balanga',
                'Billiri',
                'Dukku',
                'Kaltungo',
                'Kwami',
                'Shomgom',
                'Funakaye',
                'Gombe',
                'Nafada/Bajoga',
                'Yamaltu/Delta.'
            ],
            
        ],
        'Imo' => [
            'capital' => '',
            'lgas' => [
                'Aboh-Mbaise',
                'Ahiazu-Mbaise',
                'Ehime-Mbano',
                'Ezinihitte',
                'Ideato North',
                'Ideato South',
                'Ihitte/Uboma',
                'Ikeduru',
                'Isiala Mbano',
                'Isu',
                'Mbaitoli',
                'Mbaitoli',
                'Ngor-Okpala',
                'Njaba',
                'Nwangele',
                'Nkwerre',
                'Obowo',
                'Oguta',
                'Ohaji/Egbema',
                'Okigwe',
                'Orlu',
                'Orsu',
                'Oru East',
                'Oru West',
                'Owerri-Municipal',
                'Owerri North',
                'Owerri West'
            ],
            
        ],
        'Jigawa' => [
            'capital' => '',
            'lgas' => [
                'Auyo',
                'Babura',
                'Birni Kudu',
                'Biriniwa',
                'Buji',
                'Dutse',
                'Gagarawa',
                'Garki',
                'Gumel',
                'Guri',
                'Gwaram',
                'Gwiwa',
                'Hadejia',
                'Jahun',
                'Kafin Hausa',
                'Kaugama Kazaure',
                'Kiri Kasamma',
                'Kiyawa',
                'Maigatari',
                'Malam Madori',
                'Miga',
                'Ringim',
                'Roni',
                'Sule-Tankarkar',
                'Taura',
                'Yankwashi'
            ],
            
        ],
        'Kaduna' => [
            'capital' => '',
            'lgas' => [
                'Birni-Gwari',
                'Chikun',
                'Giwa',
                'Igabi',
                'Ikara',
                'jaba',
                'Jema a',
                'Kachia',
                'Kaduna North',
                'Kaduna South',
                'Kagarko',
                'Kajuru',
                'Kaura',
                'Kauru',
                'Kubau',
                'Kudan',
                'Lere',
                'Makarfi',
                'Sabon-Gari',
                'Sanga',
                'Soba',
                'Zango-Kataf',
                'Zaria'
            ],
            
        ],
        'Kano' => [
            'capital' => '',
            'lgas' => [
                'Ajingi',
                'Albasu',
                'Bagwai',
                'Bebeji',
                'Bichi',
                'Bunkure',
                'Dala',
                'Dambatta',
                'Dawakin Kudu',
                'Dawakin Tofa',
                'Doguwa',
                'Fagge',
                'Gabasawa',
                'Garko',
                'Garum',
                'Mallam',
                'Gaya',
                'Gezawa',
                'Gwale',
                'Gwarzo',
                'Kabo',
                'Kano Municipal',
                'Karaye',
                'Kibiya',
                'Kiru',
                'kumbotso',
                'Kunchi',
                'Kura',
                'Madobi',
                'Makoda',
                'Minjibir',
                'Nasarawa',
                'Rano',
                'Rimin Gado',
                'Rogo',
                'Shanono',
                'Sumaila',
                'Takali',
                'Tarauni',
                'Tofa',
                'Tsanyawa',
                'Tudun Wada',
                'Ungogo',
                'Warawa',
                'Wudil'
            ],
            
        ],
        'Katsina' => [
            'capital' => '',
            'lgas' => [
                'Bakori',
                'Batagarawa',
                'Batsari',
                'Baure',
                'Bindawa',
                'Charanchi',
                'Dandume',
                'Danja',
                'Dan Musa',
                'Daura',
                'Dutsi',
                'Dutsin-Ma',
                'Faskari',
                'Funtua',
                'Ingawa',
                'Jibia',
                'Kafur',
                'Kaita',
                'Kankara',
                'Kankia',
                'Katsina',
                'Kurfi',
                'Kusada',
                'Mai Adua',
                'Malumfashi',
                'Mani',
                'Mashi',
                'Matazuu',
                'Musawa',
                'Rimi',
                'Sabuwa',
                'Safana',
                'Sandamu',
                'Zango'
            ],
            
        ],
        'Kebbi' => [
            'capital' => '',
            'lgas' => [
                'Aleiro',
                'Arewa-Dandi',
                'Argungu',
                'Augie',
                'Bagudo',
                'Birnin Kebbi',
                'Bunza',
                'Dandi',
                'Fakai',
                'Gwandu',
                'Jega',
                'Kalgo',
                'Koko/Besse',
                'Maiyama',
                'Ngaski',
                'Sakaba',
                'Shanga',
                'Suru',
                'Wasagu/Danko',
                'Yauri',
                'Zuru'
            ],
            
        ],
        'Kogi' => [
            'capital' => '',
            'lgas' => [
                'Adavi',
                'Ajaokuta',
                'Ankpa',
                'Bassa',
                'Dekina',
                'Ibaji',
                'Idah',
                'Igalamela-Odolu',
                'Ijumu',
                'Kabba/Bunu',
                'Kogi',
                'Lokoja',
                'Mopa-Muro',
                'Ofu',
                'Ogori/Mangongo',
                'Okehi',
                'Okene',
                'Olamabolo',
                'Omala',
                'Yagba East',
                'Yagba West'
            ],
            
        ],
        'Kwara' => [
            'capital' => '',
            'lgas' => [
                'Asa',
                'Baruten',
                'Edu',
                'Ekiti',
                'Ifelodun',
                'Ilorin East',
                'Ilorin West',
                'Irepodun',
                'Isin',
                'Kaiama',
                'Moro',
                'Offa',
                'Oke-Ero',
                'Oyun',
                'Pategi'        
            ],
            
        ],
        'Lagos' => [
            'capital' => '',
            'lgas' => [
                'Agege',
                'Ajeromi-Ifelodun',
                'Alimosho',
                'Amuwo-Odofin',
                'Apapa',
                'Badagry',
                'Epe',
                'Eti-Osa',
                'Ibeju/Lekki',
                'Ifako-Ijaye',
                'Ikeja',
                'Ikorodu',
                'Kosofe',
                'Lagos Island',
                'Lagos Mainland',
                'Mushin',
                'Ojo',
                'Oshodi-Isolo',
                'Shomolu',
                'Surulere'        
            ],
            
        ],
        'Nasarawa' => [
            'capital' => '',
            'lgas' => [
                'Akwanga',
                'Awe',
                'Doma',
                'Karu',
                'Keana',
                'Keffi',
                'Kokona',
                'Lafia',
                'Nasarawa',
                'Nasarawa-Eggon',
                'Obi',
                'Toto',
                'Wamba'        
            ],
            
        ],
        'Niger' => [
            'capital' => '',
            'lgas' => [
                'Agaie',
                'Agwara',
                'Bida',
                'Borgu',
                'Bosso',
                'Chanchaga',
                'Edati',
                'Gbako',
                'Gurara',
                'Katcha',
                'Kontagora',
                'Lapai',
                'Lavun',
                'Magama',
                'Mariga',
                'Mashegu',
                'Mokwa',
                'Muya',
                'Pailoro',
                'Rafi',
                'Rijau',
                'Shiroro',
                'Suleja',
                'Tafa',
                'Wushishi'
            ],
            
        ],
        'Ogun' => [
            'capital' => '',
            'lgas' => [
                'Abeokuta North',
                'Abeokuta South',
                'Ado-Odo/Ota',
                'Egbado North',
                'Egbado South',
                'Ewekoro',
                'Ifo',
                'Ijebu East',
                'Ijebu North',
                'Ijebu North East',
                'Ijebu Ode',
                'Ikenne',
                'Imeko-Afon',
                'Ipokia',
                'Obafemi-Owode',
                'Ogun Waterside',
                'Odeda',
                'Odogbolu',
                'Remo North',
                'Shagamu'
            ],
            
        ],
        'Ondo' => [
            'capital' => '',
            'lgas' => [
                'Akoko North East',
                'Akoko North West',
                'Akoko South Akure East',
                'Akoko South West',
                'Akure North',
                'Akure South',
                'Ese-Odo',
                'Idanre',
                'Ifedore',
                'Ilaje',
                'Ile-Oluji',
                'Okeigbo',
                'Irele',
                'Odigbo',
                'Okitipupa',
                'Ondo East',
                'Ondo West',
                'Ose',
                'Owo'
            ],
            
        ],
        'Osun' => [
            'capital' => '',
            'lgas' => [
                'Aiyedade',
                'Aiyedire',
                'Atakumosa East',
                'Atakumosa West',
                'Boluwaduro',
                'Boripe',
                'Ede North',
                'Ede South',
                'Egbedore',
                'Ejigbo',
                'Ife Central',
                'Ife East',
                'Ife North',
                'Ife South',
                'Ifedayo',
                'Ifelodun',
                'Ila',
                'Ilesha East',
                'Ilesha West',
                'Irepodun',
                'Irewole',
                'Isokan',
                'Iwo',
                'Obokun',
                'Odo-Otin',
                'Ola-Oluwa',
                'Olorunda',
                'Oriade',
                'Orolu',
                'Osogbo'
            ],
            
        ],
        'Oyo' => [
            'capital' => '',
            'lgas' => [
                'Afijio',
                'Akinyele',
                'Atiba',
                'Atigbo',
                'Egbeda',
                'Ibadan Central',
                'Ibadan North',
                'Ibadan North West',
                'Ibadan South East',
                'Ibadan South West',
                'Ibarapa Central',
                'Ibarapa East',
                'Ibarapa North',
                'Ido',
                'Irepo',
                'Iseyin',
                'Itesiwaju',
                'Iwajowa',
                'Kajola',
                'Lagelu Ogbomosho North',
                'Ogbomosho South',
                'Ogo Oluwa',
                'Olorunsogo',
                'Oluyole',
                'Ona-Ara',
                'Orelope',
                'Ori Ire',
                'Oyo East',
                'Oyo West',
                'Saki East',
                'Saki West',
                'Surulere'
            ],
            
        ],
        'Plateau' => [
            'capital' => '',
            'lgas' => [
                'Barikin Ladi',
                'Bassa',
                'Bokkos',
                'Jos East',
                'Jos North',
                'Jos South',
                'Kanam',
                'Kanke',
                'Langtang North',
                'Langtang South',
                'Mangu',
                'Mikang',
                'Pankshin',
                'Qua\'an Pan',
                'Riyom',
                'Shendam',
                'Wase'        
            ],
            
        ],
        'Rivers' => [
            'capital' => '',
            'lgas' => [
                'Abua/Odual',
                'Ahoada East',
                'Ahoada West',
                'Akuku Toru',
                'Andoni',
                'Asari-Toru',
                'Bonny',
                'Degema',
                'Emohua',
                'Eleme',
                'Etche',
                'Gokana',
                'Ikwerre',
                'Khana',
                'Obia/Akpor',
                'Ogba/Egbema/Ndoni',
                'Ogu/Bolo',
                'Okrika',
                'Omumma',
                'Opobo/Nkoro',
                'Oyigbo',
                'Port-Harcourt',
                'Tai'
            ],
            
        ],
        'Sokoto' => [
            'capital' => '',
            'lgas' => [
                'Binji',
                'Bodinga',
                'Dange-shnsi',
                'Gada',
                'Goronyo',
                'Gudu',
                'Gawabawa',
                'Illela',
                'Isa',
                'Kware',
                'kebbe',
                'Rabah',
                'Sabon birni',
                'Shagari',
                'Silame',
                'Sokoto North',
                'Sokoto South',
                'Tambuwal',
                'Tqngaza',
                'Tureta',
                'Wamako',
                'Wurno',
                'Yabo'
            ],
            
        ],
        'Taraba' => [
            'capital' => '',
            'lgas' => [
                'Ardo-kola',
                'Bali',
                'Donga',
                'Gashaka',
                'Cassol',
                'Ibi',
                'Jalingo',
                'Karin-Lamido',
                'Kurmi',
                'Lau',
                'Sardauna',
                'Takum',
                'Ussa',
                'Wukari',
                'Yorro',
                'Zing'
            ],
            
        ],
        'Yobe' => [
            'capital' => '',
            'lgas' => [
                'Bade',
                'Bursari',
                'Damaturu',
                'Fika',
                'Fune',
                'Geidam',
                'Gujba',
                'Gulani',
                'Jakusko',
                'Karasuwa',
                'Karawa',
                'Machina',
                'Nangere',
                'Nguru Potiskum',
                'Tarmua',
                'Yunusari',
                'Yusufari'
            ],
            
        ],
        'Zamfara' => [
            'capital' => '',
            'lgas' => [
                'Anka',
                'Bakura',
                'Birnin Magaji',
                'Bukkuyum',
                'Bungudu',
                'Gummi',
                'Gusau',
                'Kaura',
                'Namoda',
                'Maradun',
                'Maru',
                'Shinkafi',
                'Talata Mafara',
                'Tsafe',
                'Zurmi'        
            ],
            
        ],
        // Add other states and their LGAs
    ],
];
